# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
      - develop

variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    variables:
      - template: variables/var_pr.yml
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
            - template: jobs/validate.yml
